// flow-typed signature: 4f22bb80a3d6573c117dbb67fea6c523
// flow-typed version: <<STUB>>/cli-cursor_v2.1.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cli-cursor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cli-cursor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'cli-cursor/index' {
  declare module.exports: $Exports<'cli-cursor'>;
}
declare module 'cli-cursor/index.js' {
  declare module.exports: $Exports<'cli-cursor'>;
}
