// flow-typed signature: 64a7a56c65860fdd9e129c425b0021f7
// flow-typed version: <<STUB>>/cucumber-snippets-livescript_v1.0.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cucumber-snippets-livescript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cucumber-snippets-livescript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cucumber-snippets-livescript/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cucumber-snippets-livescript/dist/index.js' {
  declare module.exports: $Exports<'cucumber-snippets-livescript/dist/index'>;
}
