// flow-typed signature: 95e26b3799197d2f6613dd1b2a006658
// flow-typed version: <<STUB>>/cucumber_v1.3.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cucumber'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cucumber' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cucumber/bin/cucumber' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/api' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/api/scenario' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/ast' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/ast/data_table' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/ast/doc_string' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/ast/feature' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/ast/filter' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/ast/filter/any_of_names_rule' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/ast/filter/any_of_tags_rule' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/ast/filter/element_matching_tag_spec' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/ast/filter/scenario_at_line_rule' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/ast/hook_step' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/ast/scenario' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/ast/step' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/ast/tag' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/cli' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/cli/configuration' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/cli/feature_path_expander' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/cli/feature_source_loader' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/cli/path_expander' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/cli/profiles_loader' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/cli/support_code_loader' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/cli/support_code_path_expander' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/debug' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/debug/simple_ast_listener' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/events' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/listener' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/listener/formatter' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/listener/json_formatter' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/listener/pretty_formatter' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/listener/progress_formatter' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/listener/rerun_formatter' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/listener/snippets_formatter' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/listener/summary_formatter' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/parser' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/runtime' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/runtime/attachment' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/runtime/event_broadcaster' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/runtime/event' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/runtime/features_result' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/runtime/features_runner' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/runtime/scenario_result' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/runtime/scenario_runner' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/runtime/stack_trace_filter' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/runtime/step_result' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/status' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/support_code' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/support_code/hook' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/support_code/library' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/support_code/step_definition_snippet_builder' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/support_code/step_definition_snippet_builder/javascript_syntax' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/support_code/step_definition' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/tag_group_parser' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/type' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/type/hash_data_table' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/type/string' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/util' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/util/arguments' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/util/async_for_each' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/util/colors' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/util/exception' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/util/real_time' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/util/reg_exp' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/util/run' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/util/string' {
  declare module.exports: any;
}

declare module 'cucumber/lib/cucumber/volatile_configuration' {
  declare module.exports: any;
}

declare module 'cucumber/release/cucumber' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cucumber/bin/cucumber.js' {
  declare module.exports: $Exports<'cucumber/bin/cucumber'>;
}
declare module 'cucumber/lib/cucumber.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber'>;
}
declare module 'cucumber/lib/cucumber/api.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/api'>;
}
declare module 'cucumber/lib/cucumber/api/scenario.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/api/scenario'>;
}
declare module 'cucumber/lib/cucumber/ast.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/ast'>;
}
declare module 'cucumber/lib/cucumber/ast/data_table.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/ast/data_table'>;
}
declare module 'cucumber/lib/cucumber/ast/doc_string.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/ast/doc_string'>;
}
declare module 'cucumber/lib/cucumber/ast/feature.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/ast/feature'>;
}
declare module 'cucumber/lib/cucumber/ast/filter.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/ast/filter'>;
}
declare module 'cucumber/lib/cucumber/ast/filter/any_of_names_rule.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/ast/filter/any_of_names_rule'>;
}
declare module 'cucumber/lib/cucumber/ast/filter/any_of_tags_rule.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/ast/filter/any_of_tags_rule'>;
}
declare module 'cucumber/lib/cucumber/ast/filter/element_matching_tag_spec.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/ast/filter/element_matching_tag_spec'>;
}
declare module 'cucumber/lib/cucumber/ast/filter/scenario_at_line_rule.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/ast/filter/scenario_at_line_rule'>;
}
declare module 'cucumber/lib/cucumber/ast/hook_step.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/ast/hook_step'>;
}
declare module 'cucumber/lib/cucumber/ast/scenario.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/ast/scenario'>;
}
declare module 'cucumber/lib/cucumber/ast/step.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/ast/step'>;
}
declare module 'cucumber/lib/cucumber/ast/tag.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/ast/tag'>;
}
declare module 'cucumber/lib/cucumber/cli.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/cli'>;
}
declare module 'cucumber/lib/cucumber/cli/configuration.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/cli/configuration'>;
}
declare module 'cucumber/lib/cucumber/cli/feature_path_expander.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/cli/feature_path_expander'>;
}
declare module 'cucumber/lib/cucumber/cli/feature_source_loader.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/cli/feature_source_loader'>;
}
declare module 'cucumber/lib/cucumber/cli/path_expander.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/cli/path_expander'>;
}
declare module 'cucumber/lib/cucumber/cli/profiles_loader.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/cli/profiles_loader'>;
}
declare module 'cucumber/lib/cucumber/cli/support_code_loader.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/cli/support_code_loader'>;
}
declare module 'cucumber/lib/cucumber/cli/support_code_path_expander.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/cli/support_code_path_expander'>;
}
declare module 'cucumber/lib/cucumber/debug.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/debug'>;
}
declare module 'cucumber/lib/cucumber/debug/simple_ast_listener.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/debug/simple_ast_listener'>;
}
declare module 'cucumber/lib/cucumber/events.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/events'>;
}
declare module 'cucumber/lib/cucumber/listener.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/listener'>;
}
declare module 'cucumber/lib/cucumber/listener/formatter.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/listener/formatter'>;
}
declare module 'cucumber/lib/cucumber/listener/json_formatter.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/listener/json_formatter'>;
}
declare module 'cucumber/lib/cucumber/listener/pretty_formatter.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/listener/pretty_formatter'>;
}
declare module 'cucumber/lib/cucumber/listener/progress_formatter.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/listener/progress_formatter'>;
}
declare module 'cucumber/lib/cucumber/listener/rerun_formatter.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/listener/rerun_formatter'>;
}
declare module 'cucumber/lib/cucumber/listener/snippets_formatter.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/listener/snippets_formatter'>;
}
declare module 'cucumber/lib/cucumber/listener/summary_formatter.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/listener/summary_formatter'>;
}
declare module 'cucumber/lib/cucumber/parser.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/parser'>;
}
declare module 'cucumber/lib/cucumber/runtime.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/runtime'>;
}
declare module 'cucumber/lib/cucumber/runtime/attachment.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/runtime/attachment'>;
}
declare module 'cucumber/lib/cucumber/runtime/event_broadcaster.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/runtime/event_broadcaster'>;
}
declare module 'cucumber/lib/cucumber/runtime/event.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/runtime/event'>;
}
declare module 'cucumber/lib/cucumber/runtime/features_result.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/runtime/features_result'>;
}
declare module 'cucumber/lib/cucumber/runtime/features_runner.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/runtime/features_runner'>;
}
declare module 'cucumber/lib/cucumber/runtime/scenario_result.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/runtime/scenario_result'>;
}
declare module 'cucumber/lib/cucumber/runtime/scenario_runner.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/runtime/scenario_runner'>;
}
declare module 'cucumber/lib/cucumber/runtime/stack_trace_filter.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/runtime/stack_trace_filter'>;
}
declare module 'cucumber/lib/cucumber/runtime/step_result.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/runtime/step_result'>;
}
declare module 'cucumber/lib/cucumber/status.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/status'>;
}
declare module 'cucumber/lib/cucumber/support_code.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/support_code'>;
}
declare module 'cucumber/lib/cucumber/support_code/hook.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/support_code/hook'>;
}
declare module 'cucumber/lib/cucumber/support_code/library.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/support_code/library'>;
}
declare module 'cucumber/lib/cucumber/support_code/step_definition_snippet_builder.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/support_code/step_definition_snippet_builder'>;
}
declare module 'cucumber/lib/cucumber/support_code/step_definition_snippet_builder/javascript_syntax.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/support_code/step_definition_snippet_builder/javascript_syntax'>;
}
declare module 'cucumber/lib/cucumber/support_code/step_definition.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/support_code/step_definition'>;
}
declare module 'cucumber/lib/cucumber/tag_group_parser.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/tag_group_parser'>;
}
declare module 'cucumber/lib/cucumber/type.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/type'>;
}
declare module 'cucumber/lib/cucumber/type/hash_data_table.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/type/hash_data_table'>;
}
declare module 'cucumber/lib/cucumber/type/string.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/type/string'>;
}
declare module 'cucumber/lib/cucumber/util.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/util'>;
}
declare module 'cucumber/lib/cucumber/util/arguments.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/util/arguments'>;
}
declare module 'cucumber/lib/cucumber/util/async_for_each.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/util/async_for_each'>;
}
declare module 'cucumber/lib/cucumber/util/colors.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/util/colors'>;
}
declare module 'cucumber/lib/cucumber/util/exception.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/util/exception'>;
}
declare module 'cucumber/lib/cucumber/util/real_time.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/util/real_time'>;
}
declare module 'cucumber/lib/cucumber/util/reg_exp.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/util/reg_exp'>;
}
declare module 'cucumber/lib/cucumber/util/run.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/util/run'>;
}
declare module 'cucumber/lib/cucumber/util/string.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/util/string'>;
}
declare module 'cucumber/lib/cucumber/volatile_configuration.js' {
  declare module.exports: $Exports<'cucumber/lib/cucumber/volatile_configuration'>;
}
declare module 'cucumber/release/cucumber.js' {
  declare module.exports: $Exports<'cucumber/release/cucumber'>;
}
