// flow-typed signature: b48857d5d08c26b15e7646ad058da101
// flow-typed version: <<STUB>>/dashify_v1.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dashify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dashify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'dashify/index' {
  declare module.exports: $Exports<'dashify'>;
}
declare module 'dashify/index.js' {
  declare module.exports: $Exports<'dashify'>;
}
