// flow-typed signature: 88f2241cf18b5511d366c050559c292c
// flow-typed version: <<STUB>>/dim-console_v0.4.4/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dim-console'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dim-console' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dim-console/dist/dim-console' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dim-console/dist/dim-console.js' {
  declare module.exports: $Exports<'dim-console/dist/dim-console'>;
}
