// flow-typed signature: a92db308c3f064006ded0e6fe45eb02c
// flow-typed version: <<STUB>>/end-child-processes_v0.0.6/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'end-child-processes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'end-child-processes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'end-child-processes/index' {
  declare module.exports: $Exports<'end-child-processes'>;
}
declare module 'end-child-processes/index.js' {
  declare module.exports: $Exports<'end-child-processes'>;
}
