// flow-typed signature: 82c7e206572515a5743e9753d40a6bf7
// flow-typed version: <<STUB>>/eol_v0.9.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eol'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eol' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eol/eol' {
  declare module.exports: any;
}

declare module 'eol/test' {
  declare module.exports: any;
}

declare module 'eol/ui' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eol/eol.js' {
  declare module.exports: $Exports<'eol/eol'>;
}
declare module 'eol/test.js' {
  declare module.exports: $Exports<'eol/test'>;
}
declare module 'eol/ui.js' {
  declare module.exports: $Exports<'eol/ui'>;
}
