// flow-typed signature: e97bcdfb93669bfd0c3b49015541578d
// flow-typed version: <<STUB>>/greenkeeper-lockfile_v1.12.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'greenkeeper-lockfile'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'greenkeeper-lockfile' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'greenkeeper-lockfile/ci-services/bitrise' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/ci-services/buildkite' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/ci-services/circleci' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/ci-services/index' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/ci-services/jenkins' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/ci-services/tests' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/ci-services/travis' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/ci-services/wercker' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/lib/config' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/lib/extract-dependency' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/lib/git-helpers' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/lib/update-lockfile' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/test/lib/update-lockfile' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/update' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/upload' {
  declare module.exports: any;
}

// Filename aliases
declare module 'greenkeeper-lockfile/ci-services/bitrise.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/bitrise'>;
}
declare module 'greenkeeper-lockfile/ci-services/buildkite.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/buildkite'>;
}
declare module 'greenkeeper-lockfile/ci-services/circleci.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/circleci'>;
}
declare module 'greenkeeper-lockfile/ci-services/index.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/index'>;
}
declare module 'greenkeeper-lockfile/ci-services/jenkins.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/jenkins'>;
}
declare module 'greenkeeper-lockfile/ci-services/tests.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/tests'>;
}
declare module 'greenkeeper-lockfile/ci-services/travis.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/travis'>;
}
declare module 'greenkeeper-lockfile/ci-services/wercker.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/wercker'>;
}
declare module 'greenkeeper-lockfile/lib/config.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/lib/config'>;
}
declare module 'greenkeeper-lockfile/lib/extract-dependency.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/lib/extract-dependency'>;
}
declare module 'greenkeeper-lockfile/lib/git-helpers.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/lib/git-helpers'>;
}
declare module 'greenkeeper-lockfile/lib/update-lockfile.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/lib/update-lockfile'>;
}
declare module 'greenkeeper-lockfile/test/lib/update-lockfile.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/test/lib/update-lockfile'>;
}
declare module 'greenkeeper-lockfile/update.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/update'>;
}
declare module 'greenkeeper-lockfile/upload.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/upload'>;
}
