// flow-typed signature: 9240a9513a39373b634c2f79ca0bd27e
// flow-typed version: <<STUB>>/humanize-string_v1.0.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'humanize-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'humanize-string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'humanize-string/index' {
  declare module.exports: $Exports<'humanize-string'>;
}
declare module 'humanize-string/index.js' {
  declare module.exports: $Exports<'humanize-string'>;
}
