// flow-typed signature: 34a96d2ac236804cada99d4e72539dc0
// flow-typed version: <<STUB>>/humanize-string_v1.0.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'humanize-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'humanize-string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'humanize-string/index' {
  declare module.exports: $Exports<'humanize-string'>;
}
declare module 'humanize-string/index.js' {
  declare module.exports: $Exports<'humanize-string'>;
}
