// flow-typed signature: c1172a284639b01541f78b641ca87786
// flow-typed version: <<STUB>>/interpret_v1.1.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'interpret'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'interpret' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'interpret/index' {
  declare module.exports: $Exports<'interpret'>;
}
declare module 'interpret/index.js' {
  declare module.exports: $Exports<'interpret'>;
}
