// flow-typed signature: 45154638f2315567465b6a23affda51c
// flow-typed version: <<STUB>>/jsdiff-console_v2.2.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsdiff-console'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsdiff-console' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsdiff-console/dist/jsdiff-console' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsdiff-console/dist/jsdiff-console.js' {
  declare module.exports: $Exports<'jsdiff-console/dist/jsdiff-console'>;
}
