// flow-typed signature: b10814f9129626ed2568adc978b09426
// flow-typed version: <<STUB>>/just-kebab-case_v1.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'just-kebab-case'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'just-kebab-case' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'just-kebab-case/index' {
  declare module.exports: $Exports<'just-kebab-case'>;
}
declare module 'just-kebab-case/index.js' {
  declare module.exports: $Exports<'just-kebab-case'>;
}
