// flow-typed signature: bebf864e310e845fe30706e3802b28f2
// flow-typed version: <<STUB>>/just-camel-case_v3.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'just-camel-case'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'just-camel-case' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'just-camel-case/index' {
  declare module.exports: $Exports<'just-camel-case'>;
}
declare module 'just-camel-case/index.js' {
  declare module.exports: $Exports<'just-camel-case'>;
}
