// flow-typed signature: d59bf70c5af9fa8c1c1b003842936179
// flow-typed version: <<STUB>>/liftoff_v2.3.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'liftoff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'liftoff' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'liftoff/lib/build_config_name' {
  declare module.exports: any;
}

declare module 'liftoff/lib/file_search' {
  declare module.exports: any;
}

declare module 'liftoff/lib/find_config' {
  declare module.exports: any;
}

declare module 'liftoff/lib/find_cwd' {
  declare module.exports: any;
}

declare module 'liftoff/lib/parse_options' {
  declare module.exports: any;
}

declare module 'liftoff/lib/register_loader' {
  declare module.exports: any;
}

declare module 'liftoff/lib/silent_require' {
  declare module.exports: any;
}

// Filename aliases
declare module 'liftoff/index' {
  declare module.exports: $Exports<'liftoff'>;
}
declare module 'liftoff/index.js' {
  declare module.exports: $Exports<'liftoff'>;
}
declare module 'liftoff/lib/build_config_name.js' {
  declare module.exports: $Exports<'liftoff/lib/build_config_name'>;
}
declare module 'liftoff/lib/file_search.js' {
  declare module.exports: $Exports<'liftoff/lib/file_search'>;
}
declare module 'liftoff/lib/find_config.js' {
  declare module.exports: $Exports<'liftoff/lib/find_config'>;
}
declare module 'liftoff/lib/find_cwd.js' {
  declare module.exports: $Exports<'liftoff/lib/find_cwd'>;
}
declare module 'liftoff/lib/parse_options.js' {
  declare module.exports: $Exports<'liftoff/lib/parse_options'>;
}
declare module 'liftoff/lib/register_loader.js' {
  declare module.exports: $Exports<'liftoff/lib/register_loader'>;
}
declare module 'liftoff/lib/silent_require.js' {
  declare module.exports: $Exports<'liftoff/lib/silent_require'>;
}
