// flow-typed signature: 76f24057d35e9c2b4d401e3915f0bb92
// flow-typed version: <<STUB>>/livescript_v1.5.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'livescript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'livescript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'livescript/lib/ast' {
  declare module.exports: any;
}

declare module 'livescript/lib/browser' {
  declare module.exports: any;
}

declare module 'livescript/lib/command' {
  declare module.exports: any;
}

declare module 'livescript/lib/grammar' {
  declare module.exports: any;
}

declare module 'livescript/lib/index' {
  declare module.exports: any;
}

declare module 'livescript/lib/lang-ls' {
  declare module.exports: any;
}

declare module 'livescript/lib/lexer' {
  declare module.exports: any;
}

declare module 'livescript/lib/mode-ls' {
  declare module.exports: any;
}

declare module 'livescript/lib/node' {
  declare module.exports: any;
}

declare module 'livescript/lib/options' {
  declare module.exports: any;
}

declare module 'livescript/lib/parser' {
  declare module.exports: any;
}

declare module 'livescript/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'livescript/lib/ast.js' {
  declare module.exports: $Exports<'livescript/lib/ast'>;
}
declare module 'livescript/lib/browser.js' {
  declare module.exports: $Exports<'livescript/lib/browser'>;
}
declare module 'livescript/lib/command.js' {
  declare module.exports: $Exports<'livescript/lib/command'>;
}
declare module 'livescript/lib/grammar.js' {
  declare module.exports: $Exports<'livescript/lib/grammar'>;
}
declare module 'livescript/lib/index.js' {
  declare module.exports: $Exports<'livescript/lib/index'>;
}
declare module 'livescript/lib/lang-ls.js' {
  declare module.exports: $Exports<'livescript/lib/lang-ls'>;
}
declare module 'livescript/lib/lexer.js' {
  declare module.exports: $Exports<'livescript/lib/lexer'>;
}
declare module 'livescript/lib/mode-ls.js' {
  declare module.exports: $Exports<'livescript/lib/mode-ls'>;
}
declare module 'livescript/lib/node.js' {
  declare module.exports: $Exports<'livescript/lib/node'>;
}
declare module 'livescript/lib/options.js' {
  declare module.exports: $Exports<'livescript/lib/options'>;
}
declare module 'livescript/lib/parser.js' {
  declare module.exports: $Exports<'livescript/lib/parser'>;
}
declare module 'livescript/lib/util.js' {
  declare module.exports: $Exports<'livescript/lib/util'>;
}
