// flow-typed signature: 59908fe967c8c47cbee4b3c259061c8f
// flow-typed version: <<STUB>>/nitroglycerin_v1.1.2/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nitroglycerin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nitroglycerin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nitroglycerin/dist/nitroglycerin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nitroglycerin/dist/nitroglycerin.js' {
  declare module.exports: $Exports<'nitroglycerin/dist/nitroglycerin'>;
}
