// flow-typed signature: 99d75da845096ee7a35cdefaea60fa78
// flow-typed version: <<STUB>>/o-tools-livescript_v1.2.3/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'o-tools-livescript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'o-tools-livescript' {
  declare module.exports: any;
}
