// flow-typed signature: 90cf96e606bf73c7475bae20307e65af
// flow-typed version: <<STUB>>/observable-process_v3.4.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'observable-process'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'observable-process' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'observable-process/dist/observable-process' {
  declare module.exports: any;
}

// Filename aliases
declare module 'observable-process/dist/observable-process.js' {
  declare module.exports: $Exports<'observable-process/dist/observable-process'>;
}
