// flow-typed signature: fe2bd2149c3133ae61311b63e366d015
// flow-typed version: <<STUB>>/prelude-ls_v1.1.2/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prelude-ls'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prelude-ls' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prelude-ls/lib/Func' {
  declare module.exports: any;
}

declare module 'prelude-ls/lib/index' {
  declare module.exports: any;
}

declare module 'prelude-ls/lib/List' {
  declare module.exports: any;
}

declare module 'prelude-ls/lib/Num' {
  declare module.exports: any;
}

declare module 'prelude-ls/lib/Obj' {
  declare module.exports: any;
}

declare module 'prelude-ls/lib/Str' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prelude-ls/lib/Func.js' {
  declare module.exports: $Exports<'prelude-ls/lib/Func'>;
}
declare module 'prelude-ls/lib/index.js' {
  declare module.exports: $Exports<'prelude-ls/lib/index'>;
}
declare module 'prelude-ls/lib/List.js' {
  declare module.exports: $Exports<'prelude-ls/lib/List'>;
}
declare module 'prelude-ls/lib/Num.js' {
  declare module.exports: $Exports<'prelude-ls/lib/Num'>;
}
declare module 'prelude-ls/lib/Obj.js' {
  declare module.exports: $Exports<'prelude-ls/lib/Obj'>;
}
declare module 'prelude-ls/lib/Str.js' {
  declare module.exports: $Exports<'prelude-ls/lib/Str'>;
}
