// flow-typed signature: cd78b7cfaba982bf54c8a70ed0f9327d
// flow-typed version: <<STUB>>/ps-tree_v1.1.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ps-tree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ps-tree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ps-tree/bin/ps-tree' {
  declare module.exports: any;
}

declare module 'ps-tree/test/direct' {
  declare module.exports: any;
}

declare module 'ps-tree/test/exec/child' {
  declare module.exports: any;
}

declare module 'ps-tree/test/exec/parent' {
  declare module.exports: any;
}

declare module 'ps-tree/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ps-tree/bin/ps-tree.js' {
  declare module.exports: $Exports<'ps-tree/bin/ps-tree'>;
}
declare module 'ps-tree/index' {
  declare module.exports: $Exports<'ps-tree'>;
}
declare module 'ps-tree/index.js' {
  declare module.exports: $Exports<'ps-tree'>;
}
declare module 'ps-tree/test/direct.js' {
  declare module.exports: $Exports<'ps-tree/test/direct'>;
}
declare module 'ps-tree/test/exec/child.js' {
  declare module.exports: $Exports<'ps-tree/test/exec/child'>;
}
declare module 'ps-tree/test/exec/parent.js' {
  declare module.exports: $Exports<'ps-tree/test/exec/parent'>;
}
declare module 'ps-tree/test/test.js' {
  declare module.exports: $Exports<'ps-tree/test/test'>;
}
