// flow-typed signature: d61b9d3d5e9ade8a1331692988fb57f4
// flow-typed version: <<STUB>>/rechoir_v0.6.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rechoir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rechoir' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rechoir/lib/extension' {
  declare module.exports: any;
}

declare module 'rechoir/lib/normalize' {
  declare module.exports: any;
}

declare module 'rechoir/lib/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rechoir/index' {
  declare module.exports: $Exports<'rechoir'>;
}
declare module 'rechoir/index.js' {
  declare module.exports: $Exports<'rechoir'>;
}
declare module 'rechoir/lib/extension.js' {
  declare module.exports: $Exports<'rechoir/lib/extension'>;
}
declare module 'rechoir/lib/normalize.js' {
  declare module.exports: $Exports<'rechoir/lib/normalize'>;
}
declare module 'rechoir/lib/register.js' {
  declare module.exports: $Exports<'rechoir/lib/register'>;
}
