// flow-typed signature: 8c13a8e925530cd90ca94e6cdb787c99
// flow-typed version: <<STUB>>/remark-lint_v5.2.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-lint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-lint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remark-lint/lib/index' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/blockquote-indentation' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/checkbox-character-style' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/checkbox-content-indent' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/code-block-style' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/definition-case' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/definition-spacing' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/emphasis-marker' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/fenced-code-flag' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/fenced-code-marker' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/file-extension' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/final-definition' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/final-newline' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/first-heading-level' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/hard-break-spaces' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/heading-increment' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/heading-style' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/link-title-style' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/list-item-bullet-indent' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/list-item-content-indent' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/list-item-indent' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/list-item-spacing' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/maximum-heading-length' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/maximum-line-length' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-auto-link-without-protocol' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-blockquote-without-caret' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-consecutive-blank-lines' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-duplicate-definitions' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-duplicate-headings-in-section' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-duplicate-headings' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-emphasis-as-heading' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-file-name-articles' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-file-name-consecutive-dashes' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-file-name-irregular-characters' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-file-name-mixed-case' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-file-name-outer-dashes' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-heading-content-indent' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-heading-indent' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-heading-punctuation' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-html' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-inline-padding' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-literal-urls' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-missing-blank-lines' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-multiple-toplevel-headings' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-reference-like-url' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-shell-dollars' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-shortcut-reference-image' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-shortcut-reference-link' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-table-indentation' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-tabs' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-undefined-references' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/no-unused-definitions' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/ordered-list-marker-style' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/ordered-list-marker-value' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/rule-style' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/strong-marker' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/table-cell-padding' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/table-pipe-alignment' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/table-pipes' {
  declare module.exports: any;
}

declare module 'remark-lint/lib/rules/unordered-list-marker-style' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remark-lint/index' {
  declare module.exports: $Exports<'remark-lint'>;
}
declare module 'remark-lint/index.js' {
  declare module.exports: $Exports<'remark-lint'>;
}
declare module 'remark-lint/lib/index.js' {
  declare module.exports: $Exports<'remark-lint/lib/index'>;
}
declare module 'remark-lint/lib/rules.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules'>;
}
declare module 'remark-lint/lib/rules/blockquote-indentation.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/blockquote-indentation'>;
}
declare module 'remark-lint/lib/rules/checkbox-character-style.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/checkbox-character-style'>;
}
declare module 'remark-lint/lib/rules/checkbox-content-indent.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/checkbox-content-indent'>;
}
declare module 'remark-lint/lib/rules/code-block-style.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/code-block-style'>;
}
declare module 'remark-lint/lib/rules/definition-case.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/definition-case'>;
}
declare module 'remark-lint/lib/rules/definition-spacing.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/definition-spacing'>;
}
declare module 'remark-lint/lib/rules/emphasis-marker.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/emphasis-marker'>;
}
declare module 'remark-lint/lib/rules/fenced-code-flag.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/fenced-code-flag'>;
}
declare module 'remark-lint/lib/rules/fenced-code-marker.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/fenced-code-marker'>;
}
declare module 'remark-lint/lib/rules/file-extension.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/file-extension'>;
}
declare module 'remark-lint/lib/rules/final-definition.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/final-definition'>;
}
declare module 'remark-lint/lib/rules/final-newline.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/final-newline'>;
}
declare module 'remark-lint/lib/rules/first-heading-level.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/first-heading-level'>;
}
declare module 'remark-lint/lib/rules/hard-break-spaces.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/hard-break-spaces'>;
}
declare module 'remark-lint/lib/rules/heading-increment.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/heading-increment'>;
}
declare module 'remark-lint/lib/rules/heading-style.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/heading-style'>;
}
declare module 'remark-lint/lib/rules/link-title-style.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/link-title-style'>;
}
declare module 'remark-lint/lib/rules/list-item-bullet-indent.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/list-item-bullet-indent'>;
}
declare module 'remark-lint/lib/rules/list-item-content-indent.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/list-item-content-indent'>;
}
declare module 'remark-lint/lib/rules/list-item-indent.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/list-item-indent'>;
}
declare module 'remark-lint/lib/rules/list-item-spacing.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/list-item-spacing'>;
}
declare module 'remark-lint/lib/rules/maximum-heading-length.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/maximum-heading-length'>;
}
declare module 'remark-lint/lib/rules/maximum-line-length.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/maximum-line-length'>;
}
declare module 'remark-lint/lib/rules/no-auto-link-without-protocol.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-auto-link-without-protocol'>;
}
declare module 'remark-lint/lib/rules/no-blockquote-without-caret.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-blockquote-without-caret'>;
}
declare module 'remark-lint/lib/rules/no-consecutive-blank-lines.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-consecutive-blank-lines'>;
}
declare module 'remark-lint/lib/rules/no-duplicate-definitions.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-duplicate-definitions'>;
}
declare module 'remark-lint/lib/rules/no-duplicate-headings-in-section.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-duplicate-headings-in-section'>;
}
declare module 'remark-lint/lib/rules/no-duplicate-headings.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-duplicate-headings'>;
}
declare module 'remark-lint/lib/rules/no-emphasis-as-heading.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-emphasis-as-heading'>;
}
declare module 'remark-lint/lib/rules/no-file-name-articles.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-file-name-articles'>;
}
declare module 'remark-lint/lib/rules/no-file-name-consecutive-dashes.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-file-name-consecutive-dashes'>;
}
declare module 'remark-lint/lib/rules/no-file-name-irregular-characters.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-file-name-irregular-characters'>;
}
declare module 'remark-lint/lib/rules/no-file-name-mixed-case.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-file-name-mixed-case'>;
}
declare module 'remark-lint/lib/rules/no-file-name-outer-dashes.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-file-name-outer-dashes'>;
}
declare module 'remark-lint/lib/rules/no-heading-content-indent.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-heading-content-indent'>;
}
declare module 'remark-lint/lib/rules/no-heading-indent.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-heading-indent'>;
}
declare module 'remark-lint/lib/rules/no-heading-punctuation.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-heading-punctuation'>;
}
declare module 'remark-lint/lib/rules/no-html.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-html'>;
}
declare module 'remark-lint/lib/rules/no-inline-padding.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-inline-padding'>;
}
declare module 'remark-lint/lib/rules/no-literal-urls.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-literal-urls'>;
}
declare module 'remark-lint/lib/rules/no-missing-blank-lines.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-missing-blank-lines'>;
}
declare module 'remark-lint/lib/rules/no-multiple-toplevel-headings.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-multiple-toplevel-headings'>;
}
declare module 'remark-lint/lib/rules/no-reference-like-url.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-reference-like-url'>;
}
declare module 'remark-lint/lib/rules/no-shell-dollars.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-shell-dollars'>;
}
declare module 'remark-lint/lib/rules/no-shortcut-reference-image.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-shortcut-reference-image'>;
}
declare module 'remark-lint/lib/rules/no-shortcut-reference-link.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-shortcut-reference-link'>;
}
declare module 'remark-lint/lib/rules/no-table-indentation.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-table-indentation'>;
}
declare module 'remark-lint/lib/rules/no-tabs.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-tabs'>;
}
declare module 'remark-lint/lib/rules/no-undefined-references.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-undefined-references'>;
}
declare module 'remark-lint/lib/rules/no-unused-definitions.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/no-unused-definitions'>;
}
declare module 'remark-lint/lib/rules/ordered-list-marker-style.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/ordered-list-marker-style'>;
}
declare module 'remark-lint/lib/rules/ordered-list-marker-value.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/ordered-list-marker-value'>;
}
declare module 'remark-lint/lib/rules/rule-style.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/rule-style'>;
}
declare module 'remark-lint/lib/rules/strong-marker.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/strong-marker'>;
}
declare module 'remark-lint/lib/rules/table-cell-padding.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/table-cell-padding'>;
}
declare module 'remark-lint/lib/rules/table-pipe-alignment.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/table-pipe-alignment'>;
}
declare module 'remark-lint/lib/rules/table-pipes.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/table-pipes'>;
}
declare module 'remark-lint/lib/rules/unordered-list-marker-style.js' {
  declare module.exports: $Exports<'remark-lint/lib/rules/unordered-list-marker-style'>;
}
