// flow-typed signature: 3e42e4d1c115509222921ca380be5027
// flow-typed version: <<STUB>>/remark-preset-lint-recommended_v1.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-preset-lint-recommended'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-preset-lint-recommended' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-preset-lint-recommended/index' {
  declare module.exports: $Exports<'remark-preset-lint-recommended'>;
}
declare module 'remark-preset-lint-recommended/index.js' {
  declare module.exports: $Exports<'remark-preset-lint-recommended'>;
}
