// flow-typed signature: 0570f4233003e02c7120b311e9b7330c
// flow-typed version: <<STUB>>/remark-lint_v6.0.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-lint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-lint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-lint/index' {
  declare module.exports: $Exports<'remark-lint'>;
}
declare module 'remark-lint/index.js' {
  declare module.exports: $Exports<'remark-lint'>;
}
