// flow-typed signature: bd2e83db07b679650f5f4a15be838966
// flow-typed version: <<STUB>>/remove-value_v1.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remove-value'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remove-value' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remove-value/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remove-value/index' {
  declare module.exports: $Exports<'remove-value'>;
}
declare module 'remove-value/index.js' {
  declare module.exports: $Exports<'remove-value'>;
}
declare module 'remove-value/test.js' {
  declare module.exports: $Exports<'remove-value/test'>;
}
