// flow-typed signature: 3b089a8fa255fea7e8e8c537ab271737
// flow-typed version: <<STUB>>/require-yaml_v0.0.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'require-yaml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'require-yaml' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'require-yaml/examples/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'require-yaml/examples/index.js' {
  declare module.exports: $Exports<'require-yaml/examples/index'>;
}
declare module 'require-yaml/index' {
  declare module.exports: $Exports<'require-yaml'>;
}
declare module 'require-yaml/index.js' {
  declare module.exports: $Exports<'require-yaml'>;
}
