// flow-typed signature: c6110f1f459181cec99b2d4bb9132f54
// flow-typed version: <<STUB>>/require-uncached_v1.0.3/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'require-uncached'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'require-uncached' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'require-uncached/index' {
  declare module.exports: $Exports<'require-uncached'>;
}
declare module 'require-uncached/index.js' {
  declare module.exports: $Exports<'require-uncached'>;
}
