// flow-typed signature: 371bd632454afd0ae728374e9d0a565b
// flow-typed version: <<STUB>>/strip-ansi_v4.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'strip-ansi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'strip-ansi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'strip-ansi/index' {
  declare module.exports: $Exports<'strip-ansi'>;
}
declare module 'strip-ansi/index.js' {
  declare module.exports: $Exports<'strip-ansi'>;
}
