// flow-typed signature: 779bbd23982775bc0748d70767c026cb
// flow-typed version: <<STUB>>/tertestrial_v0.3.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tertestrial'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tertestrial' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tertestrial/dist/command-runner' {
  declare module.exports: any;
}

declare module 'tertestrial/dist/config-file' {
  declare module.exports: any;
}

declare module 'tertestrial/dist/helpers/error-message' {
  declare module.exports: any;
}

declare module 'tertestrial/dist/helpers/file-type' {
  declare module.exports: any;
}

declare module 'tertestrial/dist/helpers/fill-template' {
  declare module.exports: any;
}

declare module 'tertestrial/dist/helpers/is-duplicate-checker' {
  declare module.exports: any;
}

declare module 'tertestrial/dist/helpers/reset-terminal' {
  declare module.exports: any;
}

declare module 'tertestrial/dist/helpers/run-mode-checker' {
  declare module.exports: any;
}

declare module 'tertestrial/dist/index' {
  declare module.exports: any;
}

declare module 'tertestrial/dist/pipe-listener-spec' {
  declare module.exports: any;
}

declare module 'tertestrial/dist/pipe-listener' {
  declare module.exports: any;
}

declare module 'tertestrial/dist/setup-wizard' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tertestrial/dist/command-runner.js' {
  declare module.exports: $Exports<'tertestrial/dist/command-runner'>;
}
declare module 'tertestrial/dist/config-file.js' {
  declare module.exports: $Exports<'tertestrial/dist/config-file'>;
}
declare module 'tertestrial/dist/helpers/error-message.js' {
  declare module.exports: $Exports<'tertestrial/dist/helpers/error-message'>;
}
declare module 'tertestrial/dist/helpers/file-type.js' {
  declare module.exports: $Exports<'tertestrial/dist/helpers/file-type'>;
}
declare module 'tertestrial/dist/helpers/fill-template.js' {
  declare module.exports: $Exports<'tertestrial/dist/helpers/fill-template'>;
}
declare module 'tertestrial/dist/helpers/is-duplicate-checker.js' {
  declare module.exports: $Exports<'tertestrial/dist/helpers/is-duplicate-checker'>;
}
declare module 'tertestrial/dist/helpers/reset-terminal.js' {
  declare module.exports: $Exports<'tertestrial/dist/helpers/reset-terminal'>;
}
declare module 'tertestrial/dist/helpers/run-mode-checker.js' {
  declare module.exports: $Exports<'tertestrial/dist/helpers/run-mode-checker'>;
}
declare module 'tertestrial/dist/index.js' {
  declare module.exports: $Exports<'tertestrial/dist/index'>;
}
declare module 'tertestrial/dist/pipe-listener-spec.js' {
  declare module.exports: $Exports<'tertestrial/dist/pipe-listener-spec'>;
}
declare module 'tertestrial/dist/pipe-listener.js' {
  declare module.exports: $Exports<'tertestrial/dist/pipe-listener'>;
}
declare module 'tertestrial/dist/setup-wizard.js' {
  declare module.exports: $Exports<'tertestrial/dist/setup-wizard'>;
}
