// flow-typed signature: 6009cae7e8fd7f23f7d4788fc2eb6c7e
// flow-typed version: <<STUB>>/time-diff_v0.3.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'time-diff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'time-diff' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'time-diff/index' {
  declare module.exports: $Exports<'time-diff'>;
}
declare module 'time-diff/index.js' {
  declare module.exports: $Exports<'time-diff'>;
}
