// flow-typed signature: 4c7c7d1afb3650ee4f86a3470f6481eb
// flow-typed version: <<STUB>>/wait_v0.1.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wait'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wait' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wait/lib/wait' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wait/lib/wait.js' {
  declare module.exports: $Exports<'wait/lib/wait'>;
}
