// flow-typed signature: 83f121cd4306081fae54ebeb776a961e
// flow-typed version: <<STUB>>/wait-until-promise_v1.0.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wait-until-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wait-until-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'wait-until-promise/index' {
  declare module.exports: $Exports<'wait-until-promise'>;
}
declare module 'wait-until-promise/index.js' {
  declare module.exports: $Exports<'wait-until-promise'>;
}
