// flow-typed signature: 2aaef10b0cb4b6d2ef582643ed27d28d
// flow-typed version: <<STUB>>/yamljs_v0.3.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yamljs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yamljs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yamljs/cli/json2yaml' {
  declare module.exports: any;
}

declare module 'yamljs/cli/yaml2json' {
  declare module.exports: any;
}

declare module 'yamljs/dist/yaml.debug' {
  declare module.exports: any;
}

declare module 'yamljs/dist/yaml' {
  declare module.exports: any;
}

declare module 'yamljs/dist/yaml.legacy' {
  declare module.exports: any;
}

declare module 'yamljs/dist/yaml.min' {
  declare module.exports: any;
}

declare module 'yamljs/lib/Dumper' {
  declare module.exports: any;
}

declare module 'yamljs/lib/Escaper' {
  declare module.exports: any;
}

declare module 'yamljs/lib/Exception/DumpException' {
  declare module.exports: any;
}

declare module 'yamljs/lib/Exception/ParseException' {
  declare module.exports: any;
}

declare module 'yamljs/lib/Exception/ParseMore' {
  declare module.exports: any;
}

declare module 'yamljs/lib/Inline' {
  declare module.exports: any;
}

declare module 'yamljs/lib/Parser' {
  declare module.exports: any;
}

declare module 'yamljs/lib/Pattern' {
  declare module.exports: any;
}

declare module 'yamljs/lib/Unescaper' {
  declare module.exports: any;
}

declare module 'yamljs/lib/Utils' {
  declare module.exports: any;
}

declare module 'yamljs/lib/Yaml' {
  declare module.exports: any;
}

declare module 'yamljs/test/lib/jasmine-2.0.0/boot' {
  declare module.exports: any;
}

declare module 'yamljs/test/lib/jasmine-2.0.0/console' {
  declare module.exports: any;
}

declare module 'yamljs/test/lib/jasmine-2.0.0/jasmine-html' {
  declare module.exports: any;
}

declare module 'yamljs/test/lib/jasmine-2.0.0/jasmine' {
  declare module.exports: any;
}

declare module 'yamljs/test/spec/YamlSpec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yamljs/cli/json2yaml.js' {
  declare module.exports: $Exports<'yamljs/cli/json2yaml'>;
}
declare module 'yamljs/cli/yaml2json.js' {
  declare module.exports: $Exports<'yamljs/cli/yaml2json'>;
}
declare module 'yamljs/dist/yaml.debug.js' {
  declare module.exports: $Exports<'yamljs/dist/yaml.debug'>;
}
declare module 'yamljs/dist/yaml.js' {
  declare module.exports: $Exports<'yamljs/dist/yaml'>;
}
declare module 'yamljs/dist/yaml.legacy.js' {
  declare module.exports: $Exports<'yamljs/dist/yaml.legacy'>;
}
declare module 'yamljs/dist/yaml.min.js' {
  declare module.exports: $Exports<'yamljs/dist/yaml.min'>;
}
declare module 'yamljs/index' {
  declare module.exports: $Exports<'yamljs'>;
}
declare module 'yamljs/index.js' {
  declare module.exports: $Exports<'yamljs'>;
}
declare module 'yamljs/lib/Dumper.js' {
  declare module.exports: $Exports<'yamljs/lib/Dumper'>;
}
declare module 'yamljs/lib/Escaper.js' {
  declare module.exports: $Exports<'yamljs/lib/Escaper'>;
}
declare module 'yamljs/lib/Exception/DumpException.js' {
  declare module.exports: $Exports<'yamljs/lib/Exception/DumpException'>;
}
declare module 'yamljs/lib/Exception/ParseException.js' {
  declare module.exports: $Exports<'yamljs/lib/Exception/ParseException'>;
}
declare module 'yamljs/lib/Exception/ParseMore.js' {
  declare module.exports: $Exports<'yamljs/lib/Exception/ParseMore'>;
}
declare module 'yamljs/lib/Inline.js' {
  declare module.exports: $Exports<'yamljs/lib/Inline'>;
}
declare module 'yamljs/lib/Parser.js' {
  declare module.exports: $Exports<'yamljs/lib/Parser'>;
}
declare module 'yamljs/lib/Pattern.js' {
  declare module.exports: $Exports<'yamljs/lib/Pattern'>;
}
declare module 'yamljs/lib/Unescaper.js' {
  declare module.exports: $Exports<'yamljs/lib/Unescaper'>;
}
declare module 'yamljs/lib/Utils.js' {
  declare module.exports: $Exports<'yamljs/lib/Utils'>;
}
declare module 'yamljs/lib/Yaml.js' {
  declare module.exports: $Exports<'yamljs/lib/Yaml'>;
}
declare module 'yamljs/test/lib/jasmine-2.0.0/boot.js' {
  declare module.exports: $Exports<'yamljs/test/lib/jasmine-2.0.0/boot'>;
}
declare module 'yamljs/test/lib/jasmine-2.0.0/console.js' {
  declare module.exports: $Exports<'yamljs/test/lib/jasmine-2.0.0/console'>;
}
declare module 'yamljs/test/lib/jasmine-2.0.0/jasmine-html.js' {
  declare module.exports: $Exports<'yamljs/test/lib/jasmine-2.0.0/jasmine-html'>;
}
declare module 'yamljs/test/lib/jasmine-2.0.0/jasmine.js' {
  declare module.exports: $Exports<'yamljs/test/lib/jasmine-2.0.0/jasmine'>;
}
declare module 'yamljs/test/spec/YamlSpec.js' {
  declare module.exports: $Exports<'yamljs/test/spec/YamlSpec'>;
}
