build:

clean:

cuke:
cuke-lerna:

doc:
	echo custom-action-commonjs documentation tests ...
	${CURDIR}/node_modules/.bin/text-run --format=progress

fix:

lint:

unit:

test: doc
test-lerna: test

.SILENT:
