build:

clean:

cuke:
cuke-lerna:

doc:
	echo custom-action-async documentation tests ...
	${CURDIR}/node_modules/.bin/text-run --format=progress

fix:
	echo custom-action-esm auto-fixes ...
	${CURDIR}/../../node_modules/.bin/prettier --write .

lint:
	echo custom-action-esm linters ...
	${CURDIR}/../../node_modules/.bin/prettier -l .

unit:

test: doc
test-lerna: test

.SILENT:
